### ISSUE TITLE
Chocolatey package?

### ISSUE THREAD

**Issue by zardini123** [refactorsaurusrex/NoDoz#4]
## Is your feature request related to a problem? Please describe.
There isn't a specific problem, though implementing this issue would result in more accessibility to new users.

## Describe the solution you'd like
A Chocolatey package for this program would be fantastic.  I see you advertise scoop, though unfortunately I've been using chocolatey for awhile.  I (and probably other potential users) would like the command-line ease of this program without having to install a new package manager or fiddle with PATH.

Thank you!

**Comment by refactorsaurusrex** [comment]
Hey @zardini123! Thanks for the feedback. Unfortunately, I stopped developing Chocolatey packages a long time ago because their moderation process is way too much hassle. At one point, I got a moderation approval more than a _year_ after submission. I actually think scoop is a much better tool. Yes, it is yet-another-thing-to-install, but it's very fast. You will not have to mess with your path. Scoop does that automatically, just like Chocolatey. I encourage you to give scoop a shot!
